config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :posts
#  get 'posts', to: 'posts#index'
#  get 'show' ,to: 'posts#show'
#  get 'new' , to: 'posts#new'
#  get 'edit' , to: 'posts#edit'
root to: 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ActionController::Base
   #view
    def index   
        @posts = Post.all
    end 
    #view
    def show  
        @post =    Post.find(params[:id])
    end 

    #view 
    def new
        @post =    Post.new 
    end 
    
    #view
    def edit
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(post_params)
        @post.save
        redirect_to @post, notice: "post has been created!"
    end

    def update   
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to @post, notice: "post has been updated!"
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
    end
    
    def post_params
        params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/babooey.html.erb
babooey

app/views/posts/edit.html.erb
<h1>Hello edit</h1>

<%= form_for(@post) do |f| %>
<p>title:<%= f.text_field :title %></p>
<p>body:<%= f.text_area  :body %></p>
<%= f.submit %>
    <% end %>
    <%= link_to "ALL posts",posts_path%>

app/views/posts/index.html.erb
<h1>Hello index</h1>
<%= link_to  'Create_new_post',new_post_path%>
<% @posts.each do |post| %>
<p>ID:<%= post.id%></p>
<p><%= post.title%></p>
<p><%= post.body%></p>
<%= link_to  'Show_post',post_path(post) %>
<%= link_to 'Update_post', edit_post_path(post)%>
<p><%= link_to 'Delete', post,method:  :delete ,data: {confirm:"Are you sure to delete this post"} %>
</p>
<hr>
<%end%>

app/views/posts/new.html.erb
<h1>Hello new</h1>

<%= form_for(@post) do |f| %>
<p>title:<%= f.text_field :title %></p>
<p>body:<%= f.text_area  :body %></p>
<%= f.submit %>
    <% end %>
    <%= link_to 'All Posts',posts_path%>

app/views/posts/show.html.erb
<h1>Hello show</h1>
<%= notice%>
<p>
<label>ID: </label><%= @post.id %>
</p>
<p><label>title: </label><%=@post.title%></p>

<p><label>body: </label><%=@post.body%></p>
<%= link_to 'Update post',edit_post_path(@post)%>